name: BlockDataSaver
version: '1.0'
main: com.lonleaf.blockDataSaver.BlockDataSaver
api-version: '1.20'
authors: [ lonleaf ]
depend: [NBTAPI]
description: 保存方块NBT；Save NBT of blocks.
website: Blog:lonleaf.com
