name: BlockDataSaver
version: '2.0'
main: com.lonleaf.blockDataSaver.BlockDataSaver
api-version: '1.13'
authors: [ lonleaf ]
depend: [NBTAPI]
description: Storage NBT of blocks.
website: https://github.com/lonlf/BlockDataSaver
